#!/usr/bin/python
################################################################################
#
# Merge protein_only and not_protein .gro files
#
# by Richard in 2017 for Python 2.7 MDTraj 1.8.0
#
# Changelog ([Date]):
#
################################################################################

# Packages
import os
from argparse import ArgumentParser

def main(pro, no_pro):
    # Adds the atom counts from each file on line 2 and concatenates the atom lines together
    # Deletes box xyz size contained in protein_only.gro file

    dir_path = os.path.dirname(os.path.realpath(pro))
    pro = open(pro, 'r').readlines()
    no_pro = open(no_pro, 'r').readlines()

    with open(dir_path+'/_mut.gro', 'w') as opf:
        opf.write(pro[0])
        opf.write(str(int(pro[1]) + int(no_pro[1])))
        for line in pro[2:-1]: opf.write(line)
        for line in no_pro[2:]: opf.write(line)

    # need to edit _mut.gro with gromacs: editconf -f _mut.gro -o mut_gro
    # remove _mut.gro

if __name__ == '__main__':
    parser = ArgumentParser(
    description='Merge protein_only and not_protein .gro files')

    # Here we add all our arguments, each of these will be accessible as the
    # variable args.dest in this function. When something isn't required
    # make sure to add a default value for it.
    parser.add_argument(
    '-p', dest='pro', type=str, required=True,
    help='a protein_only.gro generated by processing a pdb file with pdb2gmx')
    parser.add_argument(
    '-n', dest='nopro', type=str, required=True,
    help='a no_protein.gro file')

    args = parser.parse_args()

    main(args.pro, args.nopro)

    print 'Done merging protein_only and not_protein gro files.'
